rule "Primo VE Marc - Lsr13"
## facets off

  when
    MARC."541" has any "3,c,d,a,5" AND (
      MARC."541".ind"1" equals " " OR
      MARC."541".ind"1" equals "1")
  then
    create pnx."search"."lsr13" with MARC "541" subfields "3,c,d,a,5"
end

rule "Primo VE Marc - Lsr13 561"
  when
     MARC."561" has any "3,a,u,5" AND (
        MARC."561".ind"1" equals " " OR
        MARC."561".ind"1" equals "1")
  then
    create pnx."search"."lsr13" with MARC "561" subfields "3,a,u,5"
end