## Display: 

rule "Primo VE - Lds10"
	when
		MARC."100" has any "a,b,c"
	then
		set TEMP"1" to MARC."100" sub without sort "a,b,c,d"
		remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
        set TEMP"2" to multilingual by "100" "Lds10" "display"
		concatenate with delimiter (TEMP"1",TEMP"2","")
		set pnx."display"."lds10" to TEMP"1"
end

rule "Primo VE - Lds10 110"
	when
		MARC."110" has any "a,b,c"
	then
		set TEMP"1" to MARC."110" sub without sort "a,b,c,d"
		remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
        set TEMP"2" to multilingual by "110" "Lds10" "display"
		concatenate with delimiter (TEMP"1",TEMP"2","")
		set pnx."display"."lds10" to TEMP"1"
end

rule "Primo VE - Lds10 111"
	when
		MARC."111" has any "a,b,c"
	then
		set TEMP"1" to MARC."111" sub without sort "a,b,c,d"
		remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
        set TEMP"2" to multilingual by "111" "Lds10" "display"
		concatenate with delimiter (TEMP"1",TEMP"2","")
		set pnx."display"."lds10" to TEMP"1"
end

rule "Primo VE - Lds10 880-100"
	when
		MARC."880" has any "a,b,c,d,n" AND
		MARC."880"."6" match "100-.*"
	then
		set TEMP"1" to MARC."880" sub without sort "a,b,c,d,n"
		remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
		set TEMP"2" to multilingual by "880" "Lds10" "display"
		concatenate with delimiter (TEMP"1",TEMP"2","")
		set pnx."display"."lds10" to TEMP"1"
end

rule "Primo VE - Lds10 880-110"
	when
		MARC."880" has any "a,b,c,d,n" AND
		MARC."880"."6" match "110-.*"
	then
		set TEMP"1" to MARC."880" sub without sort "a,b,c,d,n"
		remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
		set TEMP"2" to multilingual by "880" "Lds10" "display"
		concatenate with delimiter (TEMP"1",TEMP"2","")
		set pnx."display"."lds10" to TEMP"1"
end

rule "Primo VE - Lds10 880-111"
	when
		MARC."880" has any "a,b,c,d,n" AND
		MARC."880"."6" match "111-.*"
	then
		set TEMP"1" to MARC."880" sub without sort "a,b,c,d,n"
		remove substring using regex (TEMP"1","(/|:|;|=|,)+$")
		set TEMP"2" to multilingual by "880" "Lds10" "display"
		concatenate with delimiter (TEMP"1",TEMP"2","")
		set pnx."display"."lds10" to TEMP"1"
end