rule "Primo VE - Genre 655"
  when
    MARC."655" has any "a-b,v-z"
  then
    create pnx."display"."genre" with MARC."655" subfields "a-b,v-z"
end

rule "Primo VE - Genre 694"
  when
    MARC is "694"
  then
    create pnx."display"."genre" with MARC."694" subfields
end

rule "Primo VE - Genre 880-655"
  when
    MARC."880" has any "a-b,v-z" AND
    MARC."880"."6" match "655-.*"
  then
    create pnx."display"."genre" with MARC."880" subfields "a-b,v-z"
end

rule "Primo VE - Genre 880-694"
  when
    MARC is "880" AND
    MARC."880"."6" match "694-.*"
  then
    create pnx."display"."genre" with MARC."880" subfields
end