rule "Primo VE - Identifier 020"
	when
		MARC is "020"."a"
	then
		set TEMP"1" to MARC "020"."a"
		add prefix (TEMP"1","$$CISBN$$V")
		create pnx."display"."identifier" with TEMP"1"
end

rule "Primo VE - Identifier 022"
	when
		MARC is "022"."a"
	then
		set TEMP"1" to MARC "022"."a"
		add prefix (TEMP"1","$$CISSN$$V")
		create pnx."display"."identifier" with TEMP"1"
end

rule "Primo VE - Identifier 024"
	when
		MARC is "024"."a" AND
		MARC."024".ind"1"  equals "2"
	then
		set TEMP"1" to MARC "024"."a"
		add prefix (TEMP"1","$$CISMN$$V")
		create pnx."display"."identifier" with TEMP"1"
end