## Display: Frequency

rule "Primo VE - frequency"
  when
    MARC."310" has any "a,b"
  then
    set TEMP"1" to MARC "310" subfields "a,b"
      add prefix (TEMP"1","<i>Current</i>: ")
    create pnx."display"."frequency" with TEMP"1"
end

rule "Primo VE - frequency 321"
  when
    MARC."321" has any "a,b"
  then
    set TEMP"1" to MARC "321" subfields "a,b"
      add prefix (TEMP"1","<i>Former</i>: ")
    create pnx."display"."frequency" with TEMP"1"
end