## Display: Genre

rule "Primo VE - Genre 655"
  priority 0
  when
    MARC."655" has any "a-z"
  then
    set TEMP"1" to MARC."655" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."655" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "655" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."genre" with TEMP"1"
end

rule "Primo VE - Genre 694"
  priority 1
  when
    MARC."694" has any "a-z"
  then
    set TEMP"1" to MARC."694" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."694" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "694" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."genre" with TEMP"1"
end

rule "Primo VE - Genre 880-655"
  priority 0
  when
    MARC."880" has any "a-z" AND
    MARC."880"."6" match "655-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Genre" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."genre" with TEMP"1"
end

rule "Primo VE - Genre 880-694"
  priority 1
  when
    MARC."880" has any "a-z" AND
    MARC."880"."6" match "694-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Genre" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."genre" with TEMP"1"
end