## Display: Local Notes
## using pre-indexed data for search/facets

rule "Primo VE - Lds05"
  when
    MARC is "590"."a"
  then
    set TEMP"1" to MARC "590" subfields "a"
    add suffix (TEMP"1","<br class='note'><br class='note'>")
    create pnx."display"."lds05" with TEMP"1"
end

rule "Primo VE - Lds051"
  when
    MARC is "591"."a"
  then
    set TEMP"1" to MARC "591" subfields "a"
    add suffix (TEMP"1","<br class='note'><br class='note'>")
    create pnx."display"."lds05" with TEMP"1"
end