## Display: Subjects

rule "Primo VE Display - Subject 600"
  priority 0
  when
    MARC."600" has any "a-z" AND NOT
    MARC."600".ind"2" equals "2"
  then
    set TEMP"1" to MARC."600" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."600" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "600" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 610"
  priority 1
  when
    MARC."610" has any "a-z" AND NOT
    MARC."610".ind"2" equals "2"
	then
    set TEMP"1" to MARC."610" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."610" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "610" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 611"
  priority 2
  when
    MARC."611" has any "a-z" AND NOT
    MARC."611".ind"2" equals "2"
  then
    set TEMP"1" to MARC."611" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."611" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "611" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 630"
  priority 3
  when
    MARC."630" has any "a-z" AND NOT
    MARC."630".ind"2" equals "2"
  then
    set TEMP"1" to MARC."630" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."630" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
      kormarc remove nonfiling brackets MARC."630" sourcetag "630" from TEMP"1"
    set TEMP"3" to multilingual by "630" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","") 
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 650"
  priority 4
  when
    MARC."650" has any "a-z" AND NOT
    MARC."650".ind"2" equals "2"
  then
    set TEMP"1" to MARC."650" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."650" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "650" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Prima_Display - Subject 651"
  priority 5
  when
    MARC."651" has any "a-z" AND NOT
    MARC."651".ind"2" equals "2"  
  then
    set TEMP"1" to MARC."651" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."651" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "651" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create operational."prima_display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 690"
  priority 6
  when
    MARC."690" has any "a-z"
  then
    set TEMP"1" to MARC."690" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."690" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "690" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Prima_Display - Subject 691"
  priority 7
  when
    MARC."691" has any "a-z" AND NOT
    MARC."691".ind"2" equals "2"  
  then
    set TEMP"1" to MARC."691" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."691" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "691" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create operational."prima_display"."subject" with TEMP"1"
end

rule "Primo VE Display - Subject 696"
  priority 8
  when
    MARC."696" has any "a-z" AND NOT
    MARC."696".ind"2" equals "2"
  then
    set TEMP"1" to MARC."696" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."696" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "696" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 697"
  priority 9
  when
    MARC."697" has any "a-z" AND NOT
    MARC."697".ind"2" equals "2"
	then
    set TEMP"1" to MARC."697" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."697" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "697" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 698"
  priority 10
  when
    MARC."698" has any "a-z" AND NOT
    MARC."698".ind"2" equals "2"
  then
    set TEMP"1" to MARC."698" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."698" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "698" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 699"
  priority 11
  when
    MARC."699" has any "a-z" AND NOT
    MARC."699".ind"2" equals "2"
  then
    set TEMP"1" to MARC."699" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."699" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
      kormarc remove nonfiling brackets MARC."699" sourcetag "699" from TEMP"1"
    set TEMP"3" to multilingual by "699" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","") 
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 880-600"
  priority 0
  when
    MARC."880" has any "a-z" AND NOT
    MARC."880".ind"2" equals "2" AND
    MARC."880"."6" match "600-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 880-610"
  priority 1
  when
    MARC."880" has any "a-z" AND NOT
    MARC."880".ind"2" equals "2" AND
    MARC."880"."6" match "610-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 880-611"
  priority 2
  when
    MARC."880" has any "a-z" AND NOT
    MARC."880".ind"2" equals "2" AND
    MARC."880"."6" match "611-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 880-630"
  priority 3
  when
    MARC."880" has any "a-z" AND NOT
    MARC."880".ind"2" equals "2" AND
    MARC."880"."6" match "630-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 880-650"
  priority 4
  when
    MARC."880" has any "a-z" AND NOT
    MARC."880".ind"2" equals "2" AND
    MARC."880"."6" match "650-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end

rule "Primo VE Display- Subject 880-651"
  priority 5
  when
    MARC."880" has any "a-z" AND NOT
    MARC."880".ind"2" equals "2" AND
    MARC."880"."6" match "651-.*"
  then
    set TEMP"1" to MARC."880" sub without sorting "a-u" delimited by " "
      remove substring using regex (TEMP"1","\\.+$")
    set TEMP"2" to MARC."880" sub without sorting "v-z" delimited by " -- "
      remove substring using regex (TEMP"2","\\.+$")
      concatenate with delimiter (TEMP"1",TEMP"2"," -- ")
    set TEMP"3" to multilingual by "880" "Subject" "display"
      concatenate with delimiter (TEMP"1",TEMP"3","")
    create pnx."display"."subject" with TEMP"1"
end