## Display: Title

rule "Primo VE - Title"
  when
    MARCRECORD AND
    MARC."245" has any "c"
  then
    set TEMP"1" to prima display title
      remove string (TEMP"1","<<")
      remove string (TEMP"1",">>")
    set TEMP"2" to MARC."245" subfields "c"
      concatenate with delimiter (TEMP"1",TEMP"2","")
    create pnx."display"."title" with TEMP"1"
end

rule "Primo VE - Title1"
  when
    MARCRECORD AND NOT
    MARC."245" has any "c"
  then
    set TEMP"1" to prima display title
      remove string (TEMP"1","<<")
      remove string (TEMP"1",">>")
    create pnx."display"."title" with TEMP"1"
end